services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopping
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/shopping
    volumes:
      - ./src:/app/src
    depends_on:
      - db
volumes:
  db_data:
